### ISSUE TITLE
if image is too large 

### ISSUE THREAD

**Issue by goldengrape** [susam/texme#3]
If the size of the image is too large, it may be wider than the default text width.
Of course, by adding a line of such code can be solved.
```<style>img {width: 100%;}</style>```

**Comment by susam** [comment]
Hi @Nayan-Das,

Yes, it would be of great help. A request: Please keep the change as small as possible. I think this should be a small change in the CSS code present in the `viewer` property of `styles` variable.

**Comment by susam** [comment]
Fixed in commit 1583dde989183ce7483e6e96d1431f86b83850be.

**Comment by susam** [comment]
Fix available in version [0.6.0](https://cdn.jsdelivr.net/npm/texme@0.6.0).
