### ISSUE TITLE
Use minified commonmark

### ISSUE THREAD

**Issue by JobLeonard** [susam/texme#4]
Currently TeXMe links to:

https://cdnjs.cloudflare.com/ajax/libs/commonmark/0.28.1/commonmark.js

This is a bit over 40KiB (gzip compressed). The minified version shaves off another 10 KiB:

https://cdnjs.cloudflare.com/ajax/libs/commonmark/0.28.1/commonmark.min.js

**Comment by susam** [comment]
Fixed in commit 345f7b95437827adfb599dae42bc96e009ab1675.

**Comment by susam** [comment]
Fix available in [version 0.6.0](https://cdn.jsdelivr.net/npm/texme@0.6.0).
